FROM eclipse-temurin:17-jdk-focal
MAINTAINER abraham.hernandez
COPY target/springboot-mongodb-crud-0.0.1-SNAPSHOT.jar springboot-mongodb-crud-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/springboot-mongodb-crud-0.0.1-SNAPSHOT.jar"]